import React from 'react'

export default function AboutUS() {
  return (
    <div style={{margin: '0rem 1rem', marginTop: '-1rem'}}>
      <h1>Know us better</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae maiores officia commodi eum repellat modi. Labore odio nulla voluptas itaque odit, est soluta fugit expedita quibusdam. Quisquam fuga maiores distinctio, odio ipsum sapiente quia voluptates? Facilis maiores similique aliquid cum reiciendis architecto blanditiis voluptatum commodi dolore! Magnam temporibus modi rerum aliquam et vel? Dolores adipisci, tempora corrupti quaerat assumenda labore exercitationem aperiam pariatur officia eveniet. Itaque eius sunt nihil quam maiores repudiandae provident quo temporibus mollitia laboriosam enim dolor totam dolores cupiditate, cum officiis quod doloremque quaerat unde illo! Ipsum cupiditate blanditiis ad laborum enim neque officia, et beatae ducimus recusandae. Dicta doloribus odit quaerat sint sapiente laudantium iste corporis possimus atque magni architecto eveniet impedit aliquam sunt neque debitis distinctio odio, sequi exercitationem maiores ipsum praesentium expedita? Omnis non velit voluptatibus expedita nesciunt nemo cum tempora ea minima quod impedit et illum qui ratione quasi sequi vel, nisi debitis? Asperiores corporis inventore quasi aut. Pariatur magnam aperiam eaque! Suscipit, sapiente voluptatibus libero perspiciatis, nostrum quos veritatis officia dolor nisi et temporibus laborum, vitae dolore qui? Sequi ex provident minima ab nemo enim? Id exercitationem quis in nobis repudiandae tenetur reiciendis aliquid eaque cumque ipsum, voluptatum odio veniam similique, molestiae enim architecto aut officia corrupti ea deserunt? Excepturi magnam esse numquam perspiciatis odit enim ipsam reiciendis laudantium dolorem consequuntur quae facilis labore inventore, exercitationem nam repellat ex unde voluptates iusto cumque quo perferendis at laborum. Corporis quod soluta fuga dolores mollitia consectetur ab repudiandae nisi perspiciatis est. Earum porro architecto, asperiores officia eveniet consequatur natus repudiandae distinctio quis ea dicta corporis animi velit atque debitis eum deserunt in! Totam reiciendis corporis quasi ipsa nemo impedit, repellendus iusto laudantium cumque nihil eveniet nam omnis asperiores neque voluptatem, atque, magni non ad tempora voluptate excepturi. Atque asperiores, quasi maxime recusandae odit fugiat!</p>
    </div>
  )
}
